# Build
highlighter: null
gems:
  - jekyll-redirect-from
safe: true

# Permalinks
permalink: /Blog/:title

# SASS/SCSS
sass:
  sass_dir: static/_sass
  style: compressed

# Site settings
title: Dewep.net
baseurl: ""
url: "http://www.dewep.net"
github_username: Dewep
