# Build
highlighter: null
gems:
  - jekyll-redirect-from
#safe: true

# Permalinks
permalink: /Blog/:title

# SASS/SCSS
sass:
  sass_dir: static/_sass
  style: compressed

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "http://jekyll.github.io"
twitter_username: jekyllrb
github_username:  jekyll
